name: Build .NET DLL

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build DLL
        run: dotnet build --configuration Release --output ./bin/Release
      - name: Zip DLL and dependencies
        run: 7z a -tzip dependencies.zip ./bin/Release/*.dll
